#!/bin/sh
set -eu

deploy_dir="${SEEDSHIFT_DEPLOY_DIR:-$HOME/seedshift-radio-deploy}"
compose_file="${deploy_dir}/compose.yml"
env_file="${deploy_dir}/.env"

mkdir -p "$deploy_dir"
cp infra/compose/compose.prod.yml "$compose_file"

umask 077
cat > "$env_file" <<EOF
SEEDSHIFT_COMPOSE_PROJECT_NAME=${SEEDSHIFT_COMPOSE_PROJECT_NAME:-seedshift-radio}
SEEDSHIFT_SERVER_IMAGE=${SEEDSHIFT_SERVER_IMAGE}
SEEDSHIFT_WEB_IMAGE=${SEEDSHIFT_WEB_IMAGE}
SEEDSHIFT_SERVER_CONTAINER_NAME=${SEEDSHIFT_SERVER_CONTAINER_NAME:-seedshift-radio-server}
SEEDSHIFT_WEB_CONTAINER_NAME=${SEEDSHIFT_WEB_CONTAINER_NAME:-seedshift-radio-web}
SEEDSHIFT_RADIO_SERVER_BIND=${SEEDSHIFT_RADIO_SERVER_BIND:-127.0.0.1}
SEEDSHIFT_RADIO_SERVER_PORT=${SEEDSHIFT_RADIO_SERVER_PORT:-8080}
SEEDSHIFT_RADIO_DB_HOST=${SEEDSHIFT_RADIO_DB_HOST:-127.0.0.1}
SEEDSHIFT_RADIO_DB_PORT=${SEEDSHIFT_RADIO_DB_PORT:-5432}
SEEDSHIFT_RADIO_DB_NAME=${SEEDSHIFT_RADIO_DB_NAME:-seedshift_radio}
SEEDSHIFT_RADIO_DB_USERNAME=${SEEDSHIFT_RADIO_DB_USERNAME:-seedshift}
SEEDSHIFT_RADIO_DB_PASSWORD=${SEEDSHIFT_RADIO_DB_PASSWORD}
SEEDSHIFT_ADMIN_TOKEN=${SEEDSHIFT_ADMIN_TOKEN}
SEEDSHIFT_RADIO_CONFIG_PATH=${SEEDSHIFT_RADIO_CONFIG_PATH:-/var/lib/seedshift-radio/config/config.json}
SEEDSHIFT_RADIO_DATA_VOLUME=${SEEDSHIFT_RADIO_DATA_VOLUME:-seedshift-radio-data}
SEEDSHIFT_RADIO_JOBRUNR_ENABLED=${SEEDSHIFT_RADIO_JOBRUNR_ENABLED:-true}
SEEDSHIFT_WEB_HOSTNAME=${SEEDSHIFT_WEB_HOSTNAME:-0.0.0.0}
SEEDSHIFT_WEB_PORT=${SEEDSHIFT_WEB_PORT:-3000}
NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-/api-proxy}
SERVER_INTERNAL_API_BASE_URL=${SERVER_INTERNAL_API_BASE_URL:-http://127.0.0.1:8080}
EOF

printf '%s\n' "$deploy_dir"
